# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_queue.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11order_queue.proto\x12\x0border_queue\"\xb7\x01\n\x0e\x45nqueueRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0c\n\x04user\x18\x02 \x01(\t\x12\r\n\x05items\x18\x03 \x03(\t\x12\x42\n\x0cvector_clock\x18\x04 \x03(\x0b\x32,.order_queue.EnqueueRequest.VectorClockEntry\x1a\x32\n\x10VectorClockEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\xa7\x01\n\x0f\x45nqueueResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x43\n\x0cvector_clock\x18\x03 \x03(\x0b\x32-.order_queue.EnqueueResponse.VectorClockEntry\x1a\x32\n\x10VectorClockEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\x88\x01\n\x0e\x44\x65queueRequest\x12\x42\n\x0cvector_clock\x18\x01 \x03(\x0b\x32,.order_queue.DequeueRequest.VectorClockEntry\x1a\x32\n\x10VectorClockEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\xd6\x01\n\x0f\x44\x65queueResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x10\n\x08order_id\x18\x03 \x01(\t\x12\x0c\n\x04user\x18\x04 \x01(\t\x12\r\n\x05items\x18\x05 \x03(\t\x12\x43\n\x0cvector_clock\x18\x06 \x03(\x0b\x32-.order_queue.DequeueResponse.VectorClockEntry\x1a\x32\n\x10VectorClockEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x32\x9f\x01\n\x11OrderQueueService\x12\x44\n\x07\x45nqueue\x12\x1b.order_queue.EnqueueRequest\x1a\x1c.order_queue.EnqueueResponse\x12\x44\n\x07\x44\x65queue\x12\x1b.order_queue.DequeueRequest\x1a\x1c.order_queue.DequeueResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_queue_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ENQUEUEREQUEST_VECTORCLOCKENTRY']._options = None
  _globals['_ENQUEUEREQUEST_VECTORCLOCKENTRY']._serialized_options = b'8\001'
  _globals['_ENQUEUERESPONSE_VECTORCLOCKENTRY']._options = None
  _globals['_ENQUEUERESPONSE_VECTORCLOCKENTRY']._serialized_options = b'8\001'
  _globals['_DEQUEUEREQUEST_VECTORCLOCKENTRY']._options = None
  _globals['_DEQUEUEREQUEST_VECTORCLOCKENTRY']._serialized_options = b'8\001'
  _globals['_DEQUEUERESPONSE_VECTORCLOCKENTRY']._options = None
  _globals['_DEQUEUERESPONSE_VECTORCLOCKENTRY']._serialized_options = b'8\001'
  _globals['_ENQUEUEREQUEST']._serialized_start=35
  _globals['_ENQUEUEREQUEST']._serialized_end=218
  _globals['_ENQUEUEREQUEST_VECTORCLOCKENTRY']._serialized_start=168
  _globals['_ENQUEUEREQUEST_VECTORCLOCKENTRY']._serialized_end=218
  _globals['_ENQUEUERESPONSE']._serialized_start=221
  _globals['_ENQUEUERESPONSE']._serialized_end=388
  _globals['_ENQUEUERESPONSE_VECTORCLOCKENTRY']._serialized_start=168
  _globals['_ENQUEUERESPONSE_VECTORCLOCKENTRY']._serialized_end=218
  _globals['_DEQUEUEREQUEST']._serialized_start=391
  _globals['_DEQUEUEREQUEST']._serialized_end=527
  _globals['_DEQUEUEREQUEST_VECTORCLOCKENTRY']._serialized_start=168
  _globals['_DEQUEUEREQUEST_VECTORCLOCKENTRY']._serialized_end=218
  _globals['_DEQUEUERESPONSE']._serialized_start=530
  _globals['_DEQUEUERESPONSE']._serialized_end=744
  _globals['_DEQUEUERESPONSE_VECTORCLOCKENTRY']._serialized_start=168
  _globals['_DEQUEUERESPONSE_VECTORCLOCKENTRY']._serialized_end=218
  _globals['_ORDERQUEUESERVICE']._serialized_start=747
  _globals['_ORDERQUEUESERVICE']._serialized_end=906
# @@protoc_insertion_point(module_scope)
